---
version: "3"

services:
  collector:
    image: kaypee90/dhc-collector:0.2.0
    expose:
      - "8080"
    ports:
      - 8080:8080

  web:
    image: kaypee90/dhc-web:0.2.0
    command: npm start
    environment:
      - API_BASE_URL=http://collector:8000/v1
    expose:
      - "3000"
    ports:
      - 3000:3000
    depends_on:
      - collector
